#!/usr/bin/with-contenv sh
sh /teamspeak/sh/startup.sh

if [ -e "/teamspeak/ts3server_minimal_runscript.sh" ]
then
    if [ "$INIFILE" != 0 ]
    then
        if ! [ -e "/teamspeak/save/ts3server.ini" ]
        then 
            s6-echo "Creating ini-file .."
            exec s6-setuidgid ts /teamspeak/ts3server_minimal_runscript.sh
        fi

        s6-echo "Starting TeamSpeak 3 Server with ini file .."
        exec s6-setuidgid ts /teamspeak/ts3server_minimal_runscript.sh
    else
        s6-echo "Starting TeamSpeak 3 Server .."
        exec s6-setuidgid ts /teamspeak/ts3server_minimal_runscript.sh
    fi
fi